name: Build oracle_fdw on Windows

on:
  workflow_dispatch:   # lets you run manually
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install PostgreSQL 13
      run: |
        choco install postgresql13 --params '/Password:postgres /Port:5432 /InstallDir:C:\pgsql13'
        echo "C:\pgsql13\bin" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

    - name: Install Oracle Instant Client
      run: |
        curl -L https://download.oracle.com/otn_software/nt/instantclient/198000/instantclient-basic-windows.x64-19.8.0.0.0dbru.zip -o instantclient.zip
        curl -L https://download.oracle.com/otn_software/nt/instantclient/198000/instantclient-sdk-windows.x64-19.8.0.0.0dbru.zip -o sdk.zip
        Expand-Archive instantclient.zip -DestinationPath C:\oracle
        Expand-Archive sdk.zip -DestinationPath C:\oracle
        Rename-Item "C:\oracle\instantclient_19_8" "C:\oracle\instantclient"

    - name: Build oracle_fdw
      run: |
        cd msvc
        msbuild oracle_fdw.sln /p:Configuration=Release /p:Platform=x64 /p:PGSQL="C:\pgsql13" /p:ORACLE_HOME="C:\oracle\instantclient"

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v3
      with:
        name: oracle_fdw-dll
        path: msvc\x64\Release\oracle_fdw.dll
