name: Build oracle_fdw.dll

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout oracle_fdw
        uses: actions/checkout@v4

      - name: Install PostgreSQL 13
        run: |
          choco install postgresql13 --params '/Password=postgres' -y
          echo "C:\Program Files\PostgreSQL\13\bin" >> $env:GITHUB_PATH

      - name: Download Oracle Instant Client Basic
        run: |
          curl -L https://download.oracle.com/otn_software/nt/instantclient/1918000/instantclient-basic-windows.x64-19.18.0.0.0dbru.zip -o instantclient.zip
          mkdir C:\oracle
          tar -xf instantclient.zip -C C:\oracle
          ren "C:\oracle\instantclient_19_18" instantclient

      - name: Download Oracle Instant Client SDK
        run: |
          curl -L https://download.oracle.com/otn_software/nt/instantclient/1918000/instantclient-sdk-windows.x64-19.18.0.0.0dbru.zip -o sdk.zip
          tar -xf sdk.zip -C C:\oracle\instantclient

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build oracle_fdw
        run: |
          msbuild msvc/oracle_fdw.sln `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:PGSQL="C:\Program Files\PostgreSQL\13" `
            /p:ORACLE_HOME="C:\oracle\instantclient"

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: oracle_fdw-dll
          path: msvc/x64/Release/oracle_fdw.dll
