name: Build oracle_fdw for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout oracle_fdw
        uses: actions/checkout@v3
        with:
          repository: laurenz/oracle_fdw

      - name: Install PostgreSQL 13
        run: |
          choco install postgresql13 --yes --force
          echo "C:\Program Files\PostgreSQL\13\bin" >> $env:GITHUB_PATH

      - name: Download Oracle Instant Client (Basic + SDK)
        run: |
          curl -L https://download.oracle.com/otn_software/nt/instantclient/1916000/instantclient-basic-windows.x64-19.16.0.0.0dbru.zip -o basic.zip
          curl -L https://download.oracle.com/otn_software/nt/instantclient/1916000/instantclient-sdk-windows.x64-19.16.0.0.0dbru.zip -o sdk.zip
          mkdir C:\oracle
          tar -xf basic.zip -C C:\oracle
          tar -xf sdk.zip -C C:\oracle
          ren "C:\oracle\instantclient_19_16" instantclient
          echo "C:\oracle\instantclient" >> $env:GITHUB_PATH

      - name: Build oracle_fdw with nmake
        run: |
          cd oracle_fdw
          nmake /F Makefile.win

      - name: Upload oracle_fdw.dll
        uses: actions/upload-artifact@v4
        with:
          name: oracle_fdw-dll
          path: oracle_fdw\Release\oracle_fdw.dll